import React from 'react';
import '../App.css';
import Resume from '../images/Resume.pdf';

const Skills = () => {
  return (
    <div className='skills'>
      <section className="logoMarqueeSection">
        <div className="container" id="logoMarqueeSection">
          <div className="default-content-container flex items-center">
            <div className="default-content-container-inner marquee-wrapper relative overflow-hidden inline-block">
              <div className="marquee" style={{ animationDuration: '57s' }}>
                <a target="_blank" rel="noreferrer"><img src="https://imgs.search.brave.com/R1zlLeH1ej9qxIl5hSBBYqKRt1APS2pbgBUcZFKCSWM/rs:fit:500:0:0/g:ce/aHR0cHM6Ly91cGxv/YWQud2lraW1lZGlh/Lm9yZy93aWtpcGVk/aWEvY29tbW9ucy90/aHVtYi82LzYxL0hU/TUw1X2xvZ29fYW5k/X3dvcmRtYXJrLnN2/Zy82NDBweC1IVE1M/NV9sb2dvX2FuZF93/b3JkbWFyay5zdmcu/cG5n" title="" className="marqueelogo" style={{ width: 'auto', maxWidth: 'none' }} /></a>
                <a target="_blank" rel="noreferrer"><img src="https://imgs.search.brave.com/rUdI6j2Gl4BSRqv4T4Xe26QW1K76iQPuVxkXed6N9Hw/rs:fit:500:0:0/g:ce/aHR0cHM6Ly91cGxv/YWQud2lraW1lZGlh/Lm9yZy93aWtpcGVk/aWEvY29tbW9ucy90/aHVtYi9kL2Q1L0NT/UzNfbG9nb19hbmRf/d29yZG1hcmsuc3Zn/LzY0MHB4LUNTUzNf/bG9nb19hbmRfd29y/ZG1hcmsuc3ZnLnBu/Zw" title="" className="marqueelogo" style={{ width: 'auto', maxWidth: 'none' }} /></a>
                <a target="_blank" rel="noreferrer"><img src="https://imgs.search.brave.com/kGYjzXTWUn3Fm87enANNbxf3DRPAfnQQQXs6cMNgx0A/rs:fit:500:0:0/g:ce/aHR0cHM6Ly91cGxv/YWQud2lraW1lZGlh/Lm9yZy93aWtpcGVk/aWEvY29tbW9ucy82/LzZhL0phdmFTY3Jp/cHQtbG9nby5wbmc" title="" className="marqueelogo" style={{ width: 'auto', maxWidth: 'none' }} /></a>
                <a target="_blank" rel="noreferrer"><img src="https://imgs.search.brave.com/Uhi58my-6vKHbmLx0_Q82w7X_uwRiPQ5Jl7zfVevHLw/rs:fit:500:0:0/g:ce/aHR0cHM6Ly9jZG4w/Lmljb25maW5kZXIu/Y29tL2RhdGEvaWNv/bnMvbG9nb3MtYnJh/bmRzLWluLWNvbG9y/cy8xMjgvcmVhY3Qt/MTI4LnBuZw" title="" className="marqueelogo" style={{ width: 'auto', maxWidth: 'none' }} /></a>
                <a target="_blank" rel="noreferrer"><img src="https://imgs.search.brave.com/1uSbVQcXzqfrmBBQl2IoV_LtkH2xXY-A7Kgn7SNY934/rs:fit:500:0:0/g:ce/aHR0cHM6Ly9zZWVr/bG9nby5jb20vaW1h/Z2VzL1Yvdml0ZS1s/b2dvLUJGRDQyODM5/OTEtc2Vla2xvZ28u/Y29tLnBuZw" title="" className="marqueelogo" style={{ width: 'auto', maxWidth: 'none' }} /></a>
                <a target="_blank" rel="noreferrer"><img src="https://imgs.search.brave.com/MQbhlb93ktRVz0VvJMh18EnEZlQDcNWD8u1T8aYqeY4/rs:fit:860:0:0/g:ce/aHR0cHM6Ly9jZG4u/aWNvbnNjb3V0LmNv/bS9pY29uL2ZyZWUv/cG5nLTI1Ni9mcmVl/LWZpZ21hLTIyOTYw/NzEtMTkxMjAzMC5w/bmc_Zj13ZWJwJnc9/MTI4" title="" className="marqueelogo" style={{ width: 'auto', maxWidth: 'none' }} /></a>
                <a target="_blank" rel="noreferrer"><img src="https://imgs.search.brave.com/16OK6U5UqM2qIcpRYDhdgGfjG3Kk3ZRlocEWuvAik2c/rs:fit:500:0:0/g:ce/aHR0cHM6Ly9zdGF0/aWMtMDAuaWNvbmR1/Y2suY29tL2Fzc2V0/cy4wMC9mcmFtZXIt/aWNvbi02ODR4MTAy/NC10M2VuOGFhNC5w/bmc" title="" className="marqueelogo" style={{ width: 'auto', maxWidth: 'none' }} /></a>
                <a target="_blank" rel="noreferrer"><img src="https://imgs.search.brave.com/w1cmGQ2HDBns61MvsMLEYybuyUAe1C9IQgXhOWzF664/rs:fit:500:0:0/g:ce/aHR0cHM6Ly9zdGF0/aWMtMDAuaWNvbmR1/Y2suY29tL2Fzc2V0/cy4wMC9ub2RlLWpz/LWljb24tOTA5eDEw/MjQtaWc0Z205azcu/cG5n" title="" className="marqueelogo" style={{ width: 'auto', maxWidth: 'none' }} /></a>
                <a target="_blank" rel="noreferrer"><img src="https://imgs.search.brave.com/HXyaSNq9ZlY93SNplDP3Rd5EzH7WBmmw_C6TLYK9PvY/rs:fit:860:0:0/g:ce/aHR0cHM6Ly9raW5z/dGEuY29tL3dwLWNv/bnRlbnQvdXBsb2Fk/cy8yMDIyLzA0L2V4/cHJlc3MtMS5wbmc" title="" className="marqueelogo" style={{ width: 'auto', maxWidth: 'none' }} /></a>
                <a target="_blank" rel="noreferrer"><img src="https://imgs.search.brave.com/KburWiVRrQG1vrXJA8gn0riZT6JbCruulpg-IRWbcOQ/rs:fit:500:0:0/g:ce/aHR0cHM6Ly9hc3Nl/dHMuc3RpY2twbmcu/Y29tL2ltYWdlcy81/ODQ4MDk3OWNlZjEw/MTRjMGI1ZTQ5MDEu/cG5n" title="" className="marqueelogo" style={{ width: 'auto', maxWidth: 'none' }} /></a>
                <a target="_blank" rel="noreferrer"><img src="https://imgs.search.brave.com/JGNrn1kblW4EHP3rPIa9z5VJ7jmCpEWWe5NaKZJNikY/rs:fit:860:0:0/g:ce/aHR0cHM6Ly9wbHVz/cG5nLmNvbS9pbWct/cG5nL291dHB1dC1v/Zi1leGFtcGxlLWNy/ZWF0aW5nLXBocC1s/b2dvLXdpdGgtaW1h/Z2ljay0zMDAucG5n" title="" className="marqueelogo" style={{ width: 'auto', maxWidth: 'none' }} /></a>
                <a target="_blank" rel="noreferrer"><img src="https://imgs.search.brave.com/aYImpRYsZEyKeDeXWNdsws5Dfb4YCh8fG3bFMYEvS3k/rs:fit:500:0:0/g:ce/aHR0cHM6Ly93d3cu/bG9nby53aW5lL2Ev/bG9nby9NeVNRTC9N/eVNRTC1Mb2dvLndp/bmUuc3Zn.svg" title="" className="marqueelogo" style={{ width: 'auto', maxWidth: 'none' }} /></a>

                <a target="_blank" rel="noreferrer"><img src="https://imgs.search.brave.com/OTPZ3Z708ILDt0HNVvR9ddJEBG9TOHad_fhkJZqK6yY/rs:fit:500:0:0/g:ce/aHR0cHM6Ly9hc3Nl/dHMuc3RpY2twbmcu/Y29tL2ltYWdlcy81/ODQ4MTAyMWNlZjEw/MTRjMGI1ZTQ5NGIu/cG5n" title="" className="marqueelogo" style={{ width: 'auto', maxWidth: 'none' }} /></a>
                <a target="_blank" rel="noreferrer"><img src="https://imgs.search.brave.com/Q9AZ4cZlwiPnORUiEISojImLdxXpbgaBfaAN4pqUJ5U/rs:fit:500:0:0/g:ce/aHR0cHM6Ly91c2Vy/LWltYWdlcy5naXRo/dWJ1c2VyY29udGVu/dC5jb20vMjY3NjU3/OS8zNDk0MDU5OC0x/N2NjMjBmMC1mOWJl/LTExZTctOGM2ZC1m/MDE5MGQ1MDJkNjQu/cG5n" title="" className="marqueelogo" style={{ width: 'auto', maxWidth: 'none' }} /></a>
                <a target="_blank" rel="noreferrer"><img src="https://imgs.search.brave.com/NqTFiGguTBXv-I84u6cf0MLkNB5hyu0glxO_aUXD4kI/rs:fit:500:0:0/g:ce/aHR0cHM6Ly9hc3Nl/dHMuc3RpY2twbmcu/Y29tL2ltYWdlcy81/ODQ3Zjk4MWNlZjEw/MTRjMGI1ZTQ4YmUu/cG5n" title="" className="marqueelogo" style={{ width: 'auto', maxWidth: 'none' }} /></a>
                <a target="_blank" rel="noreferrer"><img src="https://imgs.search.brave.com/Oy_1VmfIo_2aokAJ7aSFA0mkdl_9CayA9bfY47256oY/rs:fit:500:0:0/g:ce/aHR0cHM6Ly8xMDAw/bG9nb3MubmV0L3dw/LWNvbnRlbnQvdXBs/b2Fkcy8yMDE3LzAz/L0xJTlVYLUxPR08t/NDUzeDUwMC5wbmc" title="" className="marqueelogo" style={{ width: 'auto', maxWidth: 'none' }} /></a>
                <a target="_blank" rel="noreferrer"><img src="https://imgs.search.brave.com/WHL78_weIG2Ymeyoy1DF1qVj3AiOqC470QapLB0neGo/rs:fit:860:0:0/g:ce/aHR0cHM6Ly9pLnBp/bmltZy5jb20vb3Jp/Z2luYWxzLzVjL2Ji/L2E3LzVjYmJhNzRi/NDBlYzBjMGNlNzdi/M2RiM2VjMWE1ZTA1/LnBuZw" title="" className="marqueelogo" style={{ width: 'auto', maxWidth: 'none' }} /></a>
                <a target="_blank" rel="noreferrer"><img src="https://imgs.search.brave.com/9cIcIHt8XVvOP9hh_sRsXCoDb10egyulQXxvsegGJ2g/rs:fit:860:0:0/g:ce/aHR0cHM6Ly9zZWVr/bG9nby5jb20vaW1h/Z2VzL0sva2FsaS1s/aW51eC1sb2dvLTBF/QjBCM0E4MUItc2Vl/a2xvZ28uY29tLnBu/Zw" title="" className="marqueelogo" style={{ width: 'auto', maxWidth: 'none' }} /></a>

              </div>
              <div className="marquee" style={{ animationDuration: '57s' }}>
                <a target="_blank" rel="noreferrer"><img src="https://imgs.search.brave.com/R1zlLeH1ej9qxIl5hSBBYqKRt1APS2pbgBUcZFKCSWM/rs:fit:500:0:0/g:ce/aHR0cHM6Ly91cGxv/YWQud2lraW1lZGlh/Lm9yZy93aWtpcGVk/aWEvY29tbW9ucy90/aHVtYi82LzYxL0hU/TUw1X2xvZ29fYW5k/X3dvcmRtYXJrLnN2/Zy82NDBweC1IVE1M/NV9sb2dvX2FuZF93/b3JkbWFyay5zdmcu/cG5n" title="" className="marqueelogo" style={{ width: 'auto', maxWidth: 'none' }} /></a>
                <a target="_blank" rel="noreferrer"><img src="https://imgs.search.brave.com/rUdI6j2Gl4BSRqv4T4Xe26QW1K76iQPuVxkXed6N9Hw/rs:fit:500:0:0/g:ce/aHR0cHM6Ly91cGxv/YWQud2lraW1lZGlh/Lm9yZy93aWtpcGVk/aWEvY29tbW9ucy90/aHVtYi9kL2Q1L0NT/UzNfbG9nb19hbmRf/d29yZG1hcmsuc3Zn/LzY0MHB4LUNTUzNf/bG9nb19hbmRfd29y/ZG1hcmsuc3ZnLnBu/Zw" title="" className="marqueelogo" style={{ width: 'auto', maxWidth: 'none' }} /></a>
                <a target="_blank" rel="noreferrer"><img src="https://imgs.search.brave.com/kGYjzXTWUn3Fm87enANNbxf3DRPAfnQQQXs6cMNgx0A/rs:fit:500:0:0/g:ce/aHR0cHM6Ly91cGxv/YWQud2lraW1lZGlh/Lm9yZy93aWtpcGVk/aWEvY29tbW9ucy82/LzZhL0phdmFTY3Jp/cHQtbG9nby5wbmc" title="" className="marqueelogo" style={{ width: 'auto', maxWidth: 'none' }} /></a>
                <a target="_blank" rel="noreferrer"><img src="https://imgs.search.brave.com/Uhi58my-6vKHbmLx0_Q82w7X_uwRiPQ5Jl7zfVevHLw/rs:fit:500:0:0/g:ce/aHR0cHM6Ly9jZG4w/Lmljb25maW5kZXIu/Y29tL2RhdGEvaWNv/bnMvbG9nb3MtYnJh/bmRzLWluLWNvbG9y/cy8xMjgvcmVhY3Qt/MTI4LnBuZw" title="" className="marqueelogo" style={{ width: 'auto', maxWidth: 'none' }} /></a>
                <a target="_blank" rel="noreferrer"><img src="https://imgs.search.brave.com/1uSbVQcXzqfrmBBQl2IoV_LtkH2xXY-A7Kgn7SNY934/rs:fit:500:0:0/g:ce/aHR0cHM6Ly9zZWVr/bG9nby5jb20vaW1h/Z2VzL1Yvdml0ZS1s/b2dvLUJGRDQyODM5/OTEtc2Vla2xvZ28u/Y29tLnBuZw" title="" className="marqueelogo" style={{ width: 'auto', maxWidth: 'none' }} /></a>
                <a target="_blank" rel="noreferrer"><img src="https://imgs.search.brave.com/MQbhlb93ktRVz0VvJMh18EnEZlQDcNWD8u1T8aYqeY4/rs:fit:860:0:0/g:ce/aHR0cHM6Ly9jZG4u/aWNvbnNjb3V0LmNv/bS9pY29uL2ZyZWUv/cG5nLTI1Ni9mcmVl/LWZpZ21hLTIyOTYw/NzEtMTkxMjAzMC5w/bmc_Zj13ZWJwJnc9/MTI4" title="" className="marqueelogo" style={{ width: 'auto', maxWidth: 'none' }} /></a>
                <a target="_blank" rel="noreferrer"><img src="https://imgs.search.brave.com/16OK6U5UqM2qIcpRYDhdgGfjG3Kk3ZRlocEWuvAik2c/rs:fit:500:0:0/g:ce/aHR0cHM6Ly9zdGF0/aWMtMDAuaWNvbmR1/Y2suY29tL2Fzc2V0/cy4wMC9mcmFtZXIt/aWNvbi02ODR4MTAy/NC10M2VuOGFhNC5w/bmc" title="" className="marqueelogo" style={{ width: 'auto', maxWidth: 'none' }} /></a>
                <a target="_blank" rel="noreferrer"><img src="https://imgs.search.brave.com/w1cmGQ2HDBns61MvsMLEYybuyUAe1C9IQgXhOWzF664/rs:fit:500:0:0/g:ce/aHR0cHM6Ly9zdGF0/aWMtMDAuaWNvbmR1/Y2suY29tL2Fzc2V0/cy4wMC9ub2RlLWpz/LWljb24tOTA5eDEw/MjQtaWc0Z205azcu/cG5n" title="" className="marqueelogo" style={{ width: 'auto', maxWidth: 'none' }} /></a>
                <a target="_blank" rel="noreferrer"><img src="https://imgs.search.brave.com/HXyaSNq9ZlY93SNplDP3Rd5EzH7WBmmw_C6TLYK9PvY/rs:fit:860:0:0/g:ce/aHR0cHM6Ly9raW5z/dGEuY29tL3dwLWNv/bnRlbnQvdXBsb2Fk/cy8yMDIyLzA0L2V4/cHJlc3MtMS5wbmc" title="" className="marqueelogo" style={{ width: 'auto', maxWidth: 'none' }} /></a>
                <a target="_blank" rel="noreferrer"><img src="https://imgs.search.brave.com/KburWiVRrQG1vrXJA8gn0riZT6JbCruulpg-IRWbcOQ/rs:fit:500:0:0/g:ce/aHR0cHM6Ly9hc3Nl/dHMuc3RpY2twbmcu/Y29tL2ltYWdlcy81/ODQ4MDk3OWNlZjEw/MTRjMGI1ZTQ5MDEu/cG5n" title="" className="marqueelogo" style={{ width: 'auto', maxWidth: 'none' }} /></a>
                <a target="_blank" rel="noreferrer"><img src="https://imgs.search.brave.com/JGNrn1kblW4EHP3rPIa9z5VJ7jmCpEWWe5NaKZJNikY/rs:fit:860:0:0/g:ce/aHR0cHM6Ly9wbHVz/cG5nLmNvbS9pbWct/cG5nL291dHB1dC1v/Zi1leGFtcGxlLWNy/ZWF0aW5nLXBocC1s/b2dvLXdpdGgtaW1h/Z2ljay0zMDAucG5n" title="" className="marqueelogo" style={{ width: 'auto', maxWidth: 'none' }} /></a>
                <a target="_blank" rel="noreferrer"><img src="https://imgs.search.brave.com/aYImpRYsZEyKeDeXWNdsws5Dfb4YCh8fG3bFMYEvS3k/rs:fit:500:0:0/g:ce/aHR0cHM6Ly93d3cu/bG9nby53aW5lL2Ev/bG9nby9NeVNRTC9N/eVNRTC1Mb2dvLndp/bmUuc3Zn.svg" title="" className="marqueelogo" style={{ width: 'auto', maxWidth: 'none' }} /></a>

                <a target="_blank" rel="noreferrer"><img src="https://imgs.search.brave.com/OTPZ3Z708ILDt0HNVvR9ddJEBG9TOHad_fhkJZqK6yY/rs:fit:500:0:0/g:ce/aHR0cHM6Ly9hc3Nl/dHMuc3RpY2twbmcu/Y29tL2ltYWdlcy81/ODQ4MTAyMWNlZjEw/MTRjMGI1ZTQ5NGIu/cG5n" title="" className="marqueelogo" style={{ width: 'auto', maxWidth: 'none' }} /></a>
                <a target="_blank" rel="noreferrer"><img src="https://imgs.search.brave.com/Q9AZ4cZlwiPnORUiEISojImLdxXpbgaBfaAN4pqUJ5U/rs:fit:500:0:0/g:ce/aHR0cHM6Ly91c2Vy/LWltYWdlcy5naXRo/dWJ1c2VyY29udGVu/dC5jb20vMjY3NjU3/OS8zNDk0MDU5OC0x/N2NjMjBmMC1mOWJl/LTExZTctOGM2ZC1m/MDE5MGQ1MDJkNjQu/cG5n" title="" className="marqueelogo" style={{ width: 'auto', maxWidth: 'none' }} /></a>
                <a target="_blank" rel="noreferrer"><img src="https://imgs.search.brave.com/NqTFiGguTBXv-I84u6cf0MLkNB5hyu0glxO_aUXD4kI/rs:fit:500:0:0/g:ce/aHR0cHM6Ly9hc3Nl/dHMuc3RpY2twbmcu/Y29tL2ltYWdlcy81/ODQ3Zjk4MWNlZjEw/MTRjMGI1ZTQ4YmUu/cG5n" title="" className="marqueelogo" style={{ width: 'auto', maxWidth: 'none' }} /></a>
                <a target="_blank" rel="noreferrer"><img src="https://imgs.search.brave.com/Oy_1VmfIo_2aokAJ7aSFA0mkdl_9CayA9bfY47256oY/rs:fit:500:0:0/g:ce/aHR0cHM6Ly8xMDAw/bG9nb3MubmV0L3dw/LWNvbnRlbnQvdXBs/b2Fkcy8yMDE3LzAz/L0xJTlVYLUxPR08t/NDUzeDUwMC5wbmc" title="" className="marqueelogo" style={{ width: 'auto', maxWidth: 'none' }} /></a>
                <a target="_blank" rel="noreferrer"><img src="https://imgs.search.brave.com/WHL78_weIG2Ymeyoy1DF1qVj3AiOqC470QapLB0neGo/rs:fit:860:0:0/g:ce/aHR0cHM6Ly9pLnBp/bmltZy5jb20vb3Jp/Z2luYWxzLzVjL2Ji/L2E3LzVjYmJhNzRi/NDBlYzBjMGNlNzdi/M2RiM2VjMWE1ZTA1/LnBuZw" title="" className="marqueelogo" style={{ width: 'auto', maxWidth: 'none' }} /></a>
                <a target="_blank" rel="noreferrer"><img src="https://imgs.search.brave.com/9cIcIHt8XVvOP9hh_sRsXCoDb10egyulQXxvsegGJ2g/rs:fit:860:0:0/g:ce/aHR0cHM6Ly9zZWVr/bG9nby5jb20vaW1h/Z2VzL0sva2FsaS1s/aW51eC1sb2dvLTBF/QjBCM0E4MUItc2Vl/a2xvZ28uY29tLnBu/Zw" title="" className="marqueelogo" style={{ width: 'auto', maxWidth: 'none' }} /></a>

              </div>
            </div>
          </div>
        </div>
      </section>
      <div className='button-container'>
      <button className="button-56" onClick={() => window.location.href = Resume}>View Resume</button>
      <button className='button-56'>7 Internships</button>
      </div>
    </div>
  );
}

export default Skills;
